clusterSpec:
  region: us-east-04
  scope: k8s-beta-2
  clusterOrg: cw-internal
  cni: cilium
  networkAllocations:
    podCIDRs: ["10.48.0.0/13"]
    serviceCIDRs: ["10.56.0.0/22"]
    internalLbCIDRs:
      default: 10.56.4.0/22
    externalLbCIDRs:


argocd:
  targetClusterURL: https://kube-apiserver.tenant-cw-internal-k8s-beta-2.svc.cluster.local

applications:
  appenheimer-dev:
    enabled: true
  calico:
    enabled: true
    valuesMerge:
      typha:
        replicas: 1
  coredns:
    namespace: null
    destination:
      server: https://kubernetes.default.svc
    valuesMerge:
      oob: true
      service:
        corednsOob:
          loadBalancerIP: "100.124.1.7"
      kubeconfig:
        cluster: cw-internal-beta-2
        path: /etc/kubernetes/admin-config
      secretName: internal-admin-kubeconfig
      extraServiceAnnotations:
        metallb.universe.tf/address-pool: tss
  node-local-dns:
    enabled: true
    valuesMerge:
      coreDnsOob: true
      coreDnsOobIP: "100.124.1.7"
      nldClusterIP: "10.56.0.30"
      vast:
        enabled: true
  cilium:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployCRs: false
  cilium-crs:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployLbPools: false
      clusterSpec:
        networkAllocations:
          podCIDRs: [ "10.136.0.0/13" ]
  nodepools:
    enabled: true
    values:
      nodepools:
        cpu-control-plane:
          instanceType: cd-hc-a384-genoa
  jspolicy-policies:
    values:
      policies:
        mutateNodeTypeGPU: false
  cw-node-controller:
    valuesMerge:
      nodeLifeCycle:
        zapDpu: false
  konnectivity-agent:
    enabled: false
  control-plane:
    enabled: false
  in-cluster-config:
    enabled: false
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.159"
  external-secrets:
    enabled: false
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  teleport:
    enabled: false
  traefik:
    enabled: false
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-04-coreweave-us-east-04-ngcp
          namespace: victoria-metrics
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: k8s-beta-2
            cluster_org: cw-internal
            region: us-east-04
          config:
            lokiAddress: http://100.124.0.159/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  vast-csi:
    useAllTenantsVipPool: false
  vector:
    enabled: false
