clusterSpec:
  region: us-east-04
  scope: k8s-beta-3
  clusterOrg: cw-internal
  networkAllocations:
    podCIDRs: ["10.72.0.0/13"]
    serviceCIDRs: ["10.80.0.0/22"]
    internalLbCIDRs:
      default: 10.80.4.0/22
    externalLbCIDRs:

argocd:
  targetClusterURL: https://kube-apiserver.tenant-cw-internal-k8s-beta-3.svc.cluster.local

applications:
  hpc-verification:
    enabled: false
    syncPolicy:
      automated: {}
  nodepools:
    enabled: true
    values:
      nodepools:
        cpu-control-plane:
          instanceType: cd-hc-a384-genoa
  cilium:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployCRs: false
  cilium-crs:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployLbPools: false
  jspolicy-policies:
    values:
      policies:
        mutateNodeTypeGPU: false
  cw-node-controller:
    valuesMerge:
      nodeLifeCycle:
        zapDpu: false
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.70"
  konnectivity-agent:
    enabled: false
  control-plane:
    enabled: false
  in-cluster-config:
    enabled: false
  external-secrets:
    enabled: false
  teleport:
    enabled: false
  traefik:
    enabled: false
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  vast-csi:
    useAllTenantsVipPool: false
  vector:
    enabled: false
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-04-coreweave-us-east-04-ngcp
          namespace: victoria-metrics
