clusterSpec:
  region: us-east-02
  scope: npo-canary
  clusterOrg: a74af4
  cni: cilium

argocd:
  targetClusterURL: https://kube-apiserver.tenant-a74af4-npo-canary.svc.cluster.local

applications:
  calico:
    enabled: false
  cilium:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployCRs: false
  cilium-crs:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployLbPools: false
      clusterSpec:
        networkAllocations:
          podCIDRs: [ "10.136.0.0/13" ]
  nodepools:
    enabled: true
    values:
      nodepools:
        cpu-control-plane:
          instanceType: cd-gp-a192-genoa
  jspolicy-policies:
    values:
      policies:
        mutateNodeTypeGPU: false
  cw-node-controller:
    valuesMerge:
      nodeLifeCycle:
        zapDpu: false
  konnectivity-agent:
    enabled: false
  control-plane:
    enabled: false
  coredns:
    namespace: null
    destination:
      server: https://kubernetes.default.svc
    valuesMerge:
      oob: true
      service:
        corednsOob:
          loadBalancerIP: "100.124.0.39"
      kubeconfig:
        cluster: a74af4-npo-canary
        path: /etc/kubernetes/admin-config
      secretName: admin-kubeconfig
      monitoring:
        enabled: true
      extraServiceAnnotations:
        metallb.universe.tf/address-pool: tss
  in-cluster-config:
    enabled: false
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.159"
  external-secrets:
    enabled: false
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  node-local-dns:
    valuesMerge:
      coreDnsOob: true # defaulted in app to true
      coreDnsOobIP: "100.124.0.39"
      nldClusterIP: "10.16.0.30"
      vast:
        enabled: true
  teleport:
    enabled: false
  traefik:
    enabled: false
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            region: us-east-02
        config:
          lokiAddress: http://100.124.0.159/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  # vast-csi:
  #   hasDedicatedTenant: true
  vector:
    enabled: false
  npo-cfg:
    enabled: true
  npo:
    enabled: true
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-02-coreweave-us-east-02-ngcp
          namespace: victoria-metrics
