clusterSpec:
  region: us-east-04
  scope: fleetops
  clusterOrg: cw-internal
  cni: cilium
  networkAllocations:
    externalLbCIDRs:

argocd:
  targetClusterURL: https://kube-apiserver.tenant-cw-internal-fleetops.svc.cluster.local

applications:
  fleetops-cluster:
    enabled: true
    appName: fleetops-cluster-us-east-04
  hpc-verification:
    targetRevision: fmt/hpc-verification-development
  jspolicy-policies:
    values:
      policies:
        mutateNodeTypeGPU: false
  cw-node-controller:
    valuesMerge:
      nodeLifeCycle:
        zapDpu: false
  konnectivity-agent:
    enabled: false
  calico-cleanup-controller:
    enabled: false
  cilium:
    enabled: true
    valuesMerge:
      coreweave:
        clusterSecretStores:
        externalSecrets:
  calico:
    enabled: false
  control-plane:
    enabled: false
  in-cluster-config:
    enabled: false
  coredns:
    namespace: null
    destination:
      server: https://kubernetes.default.svc
    valuesMerge:
      oob: true
      service:
        corednsOob:
          loadBalancerIP: "100.124.0.231"
      kubeconfig:
        cluster: cw-internal-fleetops
        path: /etc/kubernetes/admin-config
      secretName: internal-admin-kubeconfig
      monitoring:
        enabled: true
      extraServiceAnnotations:
        metallb.universe.tf/address-pool: tss
  node-local-dns:
    enabled: true
    valuesMerge:
      coreDnsOob: true
      coreDnsOobIP: "100.124.0.231"
      nldClusterIP: "10.16.0.30"
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.14"
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  teleport:
    enabled: false
  traefik:
    enabled: false
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: fleetops
            cluster_org: cw-internal
            region: us-east-04
          config:
            lokiAddress: http://100.124.0.14/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  vast-csi:
    useAllTenantsVipPool: false
  vector:
    enabled: false
  victoria-metrics:
    valuesMerge:
      victoria-metrics-agent:
        resources:
          requests:
            cpu: "20"
            memory: 45Gi
          limits:
            cpu: "20"
            memory: 45Gi
  npo:
    enabled: false
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-04-coreweave-us-east-04-ngcp
          namespace: victoria-metrics
