clusterSpec:
  region: us-east-08
  scope: fleetops
  clusterOrg: cw-internal
  cni: cilium
  networkAllocations:
    externalLbCIDRs:

argocd:
  targetClusterURL: https://kube-apiserver.tenant-cw-internal-fleetops.svc.cluster.local

applications:
  fleetops-cluster:
    enabled: true
    appName: fleetops-cluster-us-east-08a
    valuesMerge:
      k8sVersion: "v1.31"
  hpc-verification:
    targetRevision: fmt/hpc-verification-development
  jspolicy-policies:
    values:
      policies:
        mutateNodeTypeGPU: false
  cw-node-controller:
    valuesMerge:
      nodeLifeCycle:
        zapDpu: false
  konnectivity-agent:
    enabled: false
  calico-cleanup-controller:
    enabled: false
  cilium:
    enabled: true
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployCRs: false
  cilium-crs:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployLbPools: false
  calico:
    enabled: false
  control-plane:
    enabled: false
  in-cluster-config:
    enabled: false
  coredns:
    namespace: null
    destination:
      server: https://kubernetes.default.svc
    valuesMerge:
      oob: true
      service:
        corednsOob:
          loadBalancerIP: "100.124.0.5"
      kubeconfig:
        cluster: cw-internal-fleetops
        path: /etc/kubernetes/admin-config
      secretName: internal-admin-kubeconfig
      monitoring:
        enabled: true
      extraServiceAnnotations:
        metallb.universe.tf/address-pool: tss
  node-local-dns:
    enabled: true
    valuesMerge:
      coreDnsOob: true
      coreDnsOobIP: "100.124.0.5"
      nldClusterIP: "10.16.0.30"
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.6"
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  teleport:
    enabled: false
  traefik:
    enabled: false
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: fleetops
            cluster_org: cw-internal
            region: us-east-08
          config:
            lokiAddress: http://100.124.0.6/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  # vast-csi:
  #   hasDedicatedTenant: true
  vector:
    enabled: false
  victoria-metrics:
    valuesMerge:
      victoria-metrics-agent:
        resources:
          requests:
            cpu: "20"
            memory: 45Gi
          limits:
            cpu: "20"
            memory: 45Gi
  npo:
    enabled: false
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-08-coreweave-us-east-08a-ngcp
          namespace: victoria-metrics
