clusterSpec:
  region: us-east-03
  scope: fleetops
  clusterOrg: be1096
  cni: cilium
  networkAllocations:
    externalLbCIDRs:

argocd:
  targetClusterURL: https://kube-apiserver.tenant-be1096-fleetops.svc.cluster.local

applications:
  jspolicy-policies:
    values:
      policies:
        mutateNodeTypeGPU: false
  cw-node-controller:
    valuesMerge:
      nodeLifeCycle:
        zapDpu: false
      labelBundle:
        config:
          sku_types:
            PowerEdge_XE9680:
              fw_bundle:
                firmware: dell-h100-default-20240605.01.00.01

  konnectivity-agent:
    enabled: false
  hpc-verification:
    targetRevision: fmt/hpc-verification-development
  calico-cleanup-controller:
    enabled: false
  cilium:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.18.0
    valuesMerge:
      bgpVersion2: true
      deployCRs: false
  cilium-crs:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.18.0
    valuesMerge:
      bgpVersion2: true
      deployLbPools: false
  calico:
    enabled: false
  control-plane:
    enabled: false
  in-cluster-config:
    enabled: false
  coredns:
    namespace: null
    destination:
      server: https://kubernetes.default.svc
    valuesMerge:
      oob: true
      service:
        corednsOob:
          loadBalancerIP: "100.124.0.21"
      kubeconfig:
        cluster: be1096-fleetops
        path: /etc/kubernetes/admin-config
      secretName: internal-admin-kubeconfig
      monitoring:
        enabled: true
      extraServiceAnnotations:
        metallb.universe.tf/address-pool: tss
  node-local-dns:
    enabled: true
    valuesMerge:
      coreDnsOob: true
      coreDnsOobIP: "100.124.0.21"
      nldClusterIP: "10.16.0.30"
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.22"
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
        prometheus:
          prometheusSpec:
            remoteWrite:
              - queueConfig:
                  capacity: 10000
                  maxBackoff: 200ms
                  maxRetries: 3
                  maxSamplesPerSend: 2000
                  maxShards: 2500
                  minBackoff: 50ms
                  minShards: 50
                url: http://100.124.0.22/api/v1/push
            externalLabels:
              cluster: fleetops
              cluster_org: be1096
  teleport:
    enabled: false
  demonsrun:
    enabled: false
  traefik:
    enabled: false
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: fleetops
            cluster_org: be1096
            region: us-east-03
          config:
            lokiAddress: http://100.124.0.22/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  # vast-csi:
  #   hasDedicatedTenant: true
  vector:
    enabled: false
  npo:
    enabled: false
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-03-coreweave-us-east-03-ngcp
          namespace: victoria-metrics
