clusterSpec:
  geoRegion: na
  region: us-east-04
  objStorageRegion: lga1
  networkAllocations:
    asNumber: "4294841000"
argocd:
  customerClusters:
    a64a15-ric1:
      valueFiles:
        - values-base-k8s-1-30.yaml
        # For all new cks clusters this values file should be applied.
        - values-base-flcc-cks.yaml
    b5500f-us-east-04-prod:
      valueFiles:
        - values-base-k8s-1-29.yaml
        # For all new cks clusters this values file should be applied.
        - values-base-flcc-cks.yaml
    b5500f-staging:
      valueFiles:
        - values-base-k8s-1-30.yaml
        # For all new cks clusters this values file should be applied.
        - values-base-flcc-cks.yaml
    c3e81c-use4-prd-1:
      valueFiles:
        - values-base-k8s-1-28.yaml
        - values-base-flcc-cks.yaml
    c3e81c-use4-stg-1:
      valueFiles:
        - values-base-k8s-1-28.yaml
        - values-base-flcc-cks.yaml
    6bab75-us-shoggy-prod:
      valueFiles:
        - values-base-k8s-1-30.yaml
        # For all new cks clusters this values file should be applied.
        - values-base-flcc-cks.yaml
    6f88aa-kchai:
      valueFiles:
        - values-base-k8s-1-30.yaml
        # For all new cks clusters this values file should be applied.
        - values-base-flcc-cks.yaml
    cw-internal-fleetops:
      valueFiles:
        - values-base-k8s-1-29.yaml
        # For all fleetops clusters this value should be applied.
        - values-base-fleetops.yaml
    cw-internal-develop-eval:
      valueFiles:
        - values-base-k8s-1-30.yaml
    cw-internal-infra-poc:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    cw-internal-k8s-beta-0:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    cw-internal-k8s-beta-1:
      valueFiles:
        - values-base-k8s-1-29.yaml
        - values-base-flcc-cks.yaml
    cw-internal-k8s-beta-2:
      valueFiles:
        - values-base-k8s-1-28.yaml
        - values-base-flcc-cks.yaml
    cw-internal-k8s-beta-3:
      valueFiles:
        - values-base-k8s-1-31.yaml
        - values-base-flcc-cks.yaml
    cw-internal-sunk-dev:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    cw-internal-ml-dev:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    cw-internal-ml-poc:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    cw-internal-fleeteng-dev:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    cw-internal-biz-ops-dev:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    fe0dc0-nvh200:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    cfc69f-prod-ric1:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    c976f9-poc:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    06ce5a-qbotpoc:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    06ce5a-qbotprod:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    60e2f0-gh200:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    abb167-poc-cpu:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    abb167-poc-gpu:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    68ab39-poc:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    d43f85-mzai:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    012d16-poc:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    c5167f-prod:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    82d82b-prod:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    a951e0-prod:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    saf0d1-o11y-dev:
      valueFiles:
        - values-base-k8s-1-30.yaml
        - values-base-flcc-cks.yaml
    a74af4-redteam:
      valueFiles:
        - values-base-arm64.yaml
        - values-base-k8s-1-31.yaml
        - values-base-flcc-cks.yaml
    5e2c8b-use4-prod:
      valueFiles:
        - values-base-k8s-1-31.yaml
        - values-base-flcc-cks.yaml
    a5dd4d-cks:
      valueFiles:
        - values-base-k8s-1-31.yaml
        - values-base-flcc-cks.yaml
    bdd0a2-cks:
      valueFiles:
        - values-base-k8s-1-31.yaml
        - values-base-flcc-cks.yaml
    f0f011-poc:
      valueFiles:
        - values-base-k8s-1-31.yaml
        - values-base-flcc-cks.yaml
    cwb33f-redteam:
      valueFiles:
        - values-base-k8s-1-31.yaml
        - values-base-flcc-cks.yaml

applications:
  calico:
    valuesMerge:
      networkConfig:
        peerASN: "4210446000"
        hostCIDRs:
          - 10.176.192.0/18 # Site specific CIDR for all hosts (DPU-TO-NODE)
        networkMgmtCIDRs:
          - 10.177.0.0/19 # Site specific CIDR for network management
          - 10.250.24.0/23 # Site specific CIDR for backbone network
        dpuCIDRs:
          - 10.176.64.0/18 # Site specific CIDR for DPU BMC
          - 10.176.128.0/18 # Site specific CIDR for DPU OOB
        dpuLBCIDRs:
          - 10.177.63.0/24 # Site specific CIDR for DPU LB
        cwMgmtCIDRs:
          - 10.80.96.0/20 # Site specific CIDR for cw-mgmt
        ipmiCIDRs:
          - 10.176.0.0/18 # Site specific CIDR for host IPMI
          - 10.176.32.0/20 # Vast MGMT IP range
          - 10.176.32.0/19 # Storage MGMT
  cilium:
    valuesMerge:
      networkConfig:
        peerASN: "4210446000"
  cilium-crs:
    valuesMerge:
      networkConfig:
        peerASN: "4210446000"
  cw-node-controller:
    valuesMergeTpl: |
      features:
        DEVICESLOT_ENABLED: true
      nodeLifeCycle:
        zapDpu: true
  katalyst-operator:
    valuesMerge:
      dualDnsSupport: true
      teleportNamingOverride: us-east-04
      networkConfig:
        peerASN: "4210446000"
  node-local-dns:
    enabled: true
    valuesMerge:
      vast:
        backends:
          - name: storage-backend01
            ip: 100.121.1.21
  epimetheus:
    valuesMerge:
      slackChannelID: "C07LT4DPH6F" # epimetheus-us-east-04
  nimbus-vpc-controller:
    valuesMerge:
      cwHostPrefix: 10.176.192.0/18
      clusterSpec:
        zone: us-east-04a
        zonesEnabled: true
  vast-csi:
    hasDedicatedTenant: true
    useAllTenantsVipPool: true
    targetRevision: 1.55.0
    valuesMerge: &vast_csi_valuesMerge
      image:
        csiVastPlugin:
          tag: v2.4.2-beta-1526814
      vmsService:
        services:
          - name: vms
            endpoints:
              - ip: 10.177.32.60
  vast-csi-controller:
    valuesMerge:
      <<: *vast_csi_valuesMerge
      controller:
        tolerations:
          - key: is_cpu_compute
            operator: Exists
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node.coreweave.cloud/reserved
                      operator: In
                      values:
                        - control-plane

  npo:
    enabled: true
    valuesMerge:
      enableInstanceTypeAndTypeLabelSetting: true
  npo-cfg:
    enabled: true
  node-stitcher:
    valuesMerge:
      clusterSpec:
        zone: us-east-04a
        zonesEnabled: true
  sortinghat-api:
    valuesMerge:
      service:
        hostname: "shat.us-east-04a.int.coreweave.com,shat.us-east-04.int.coreweave.com"
  sortinghat-api-stg:
    valuesMerge:
      service:
        hostname: "shat-stg.us-east-04a.int.coreweave.com,shat-stg.us-east-04.int.coreweave.com"
  cks-worker:
    valuesMerge:
      env:
        - name: REGION
          value: us-east-04
        - name: ZONE
          value: us-east-04a
        - name: TELEPORT_OVERRIDE_ADDR
          value: teleport.us-east-04.int.coreweave.com:443
        - name: TEMPORAL_NAMESPACE
          value: cks-production.kzw3l
        - name: TEMPORAL_TARGET_HOST
          value: cks-production.kzw3l.tmprl.cloud:7233
        - name: TEMPORAL_CLIENT_CERT
          value: /var/run/ssl/certs/tls.crt
        - name: TEMPORAL_CLIENT_KEY
          value: /var/run/ssl/certs/tls.key
        - name: VAULT_ADDR
          value: https://secvault.int.coreweave.com
        - name: BUCKET_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: backblaze
              key: B2_KEY_ID
        - name: BUCKET_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backblaze
              key: B2_KEY
        - name: BUCKET_REGION
          value: us-west-004
        - name: BUCKET_PROVIDER
          value: backblaze
        - name: ENVIRONMENT
          value: prod
        - name: REGPROXY_IP
          value: 100.122.0.6
        - name: VAST_SERVICE_URL
          value: http://vrpc.us-east-04.int.coreweave.com:10540
  cks-worker-staging:
    valuesMerge:
      env:
        - name: REGION
          value: us-east-04
        - name: ZONE
          value: us-east-04a
        - name: TELEPORT_OVERRIDE_ADDR
          value: teleport.us-east-04.int.coreweave.com:443
        - name: TEMPORAL_NAMESPACE
          value: cks-test-platforms.kzw3l
        - name: TEMPORAL_TARGET_HOST
          value: cks-test-platforms.kzw3l.tmprl.cloud:7233
        - name: TEMPORAL_CLIENT_CERT
          value: /var/run/ssl/certs/tls.crt
        - name: TEMPORAL_CLIENT_KEY
          value: /var/run/ssl/certs/tls.key
        - name: VAULT_ADDR
          value: https://secvault.int.coreweave.com
        - name: BUCKET_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: B2_KEY_ID
              name: backblaze
        - name: BUCKET_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: B2_KEY
              name: backblaze
        - name: BUCKET_REGION
          value: us-west-002
        - name: BUCKET_PROVIDER
          value: backblaze
        - name: BUCKET_ENDPOINT
          value: https://s3.us-west-002.backblazeb2.com
        - name: ENVIRONMENT
          value: staging
        - name: REGPROXY_IP
          value: 100.122.0.6
  nimbus-worker:
    valuesMerge:
      env:
        - name: REGION
          value: us-east-04a
        - name: TEMPORAL_NAMESPACE
          value: cks-production.kzw3l
        - name: TEMPORAL_TARGET_HOST
          value: cks-production.kzw3l.tmprl.cloud:7233
        - name: TEMPORAL_CLIENT_CERT
          value: /var/run/ssl/certs/tls.crt
        - name: TEMPORAL_CLIENT_KEY
          value: /var/run/ssl/certs/tls.key
        - name: VAULT_ADDR
          value: https://secvault.int.coreweave.com
        - name: ENVIRONMENT
          value: prod
  nimbus-worker-staging:
    valuesMerge:
      env:
        - name: REGION
          value: us-east-04a
        - name: TEMPORAL_NAMESPACE
          value: cks-test-platforms.kzw3l
        - name: TEMPORAL_TARGET_HOST
          value: cks-test-platforms.kzw3l.tmprl.cloud:7233
        - name: TEMPORAL_CLIENT_CERT
          value: /var/run/ssl/certs/tls.crt
        - name: TEMPORAL_CLIENT_KEY
          value: /var/run/ssl/certs/tls.key
        - name: VAULT_ADDR
          value: https://secvault.int.coreweave.com
        - name: ENVIRONMENT
          value: staging
  cks-api-worker-prod:
    valuesMerge:
      env:
        - name: ZONE
          value: us-east-04a
        - name: BUCKET_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: B2_KEY_ID
              name: backblaze
        - name: BUCKET_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: B2_KEY
              name: backblaze
        - name: BUCKET_REGION
          value: us-west-004
        - name: BUCKET_PROVIDER
          value: backblaze
        - name: BUCKET_ENDPOINT
          value: https://s3.us-west-004.backblazeb2.com
        - name: ENVIRONMENT
          value: production
        - name: REGPROXY_IP
          value: 100.122.0.6
        - name: PREFIX_SERVICE_ADDR
          value: http://prefix-api-server.int.coreweave.com
        - name: TELEPORT_OVERRIDE_ADDR
          value: teleport.us-east-04.int.coreweave.com:443
  cks-api-worker-stag:
    valuesMerge:
      env:
        - name: ZONE
          value: us-east-04a
        - name: BUCKET_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: B2_KEY_ID
              name: backblaze
        - name: BUCKET_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: B2_KEY
              name: backblaze
        - name: BUCKET_REGION
          value: us-west-002
        - name: BUCKET_PROVIDER
          value: backblaze
        - name: BUCKET_ENDPOINT
          value: https://s3.us-west-002.backblazeb2.com
        - name: ENVIRONMENT
          value: staging
        - name: REGPROXY_IP
          value: 100.122.0.6
        - name: PREFIX_SERVICE_ADDR
          value: http://prefix-api-server-staging.int.coreweave.com
        - name: TELEPORT_OVERRIDE_ADDR
          value: teleport.us-east-04.int.coreweave.com:443
  vpc-api-worker-prod:
    valuesMerge:
      env:
        - name: ENVIRONMENT
          value: production
        - name: ZONE
          value: us-east-04a
        - name: VAULT_CLIENT_URL
          value: https://secvault.int.coreweave.com
        - name: VAULT_CLIENT_JWT_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: VAULT_CLIENT_SECRETS_ROLE
          value: vpc-api
        - name: DATABASE_ENDPOINT
          value: crdb-public.vpc-api.core-zero.us-east-03.int.coreweave.com
        - name: DATABASE_USER
          value: vpcapiadmin
        - name: DATABASE_INSECURE
          value: "false"
        - name: DATABASE_DATABASENAME
          value: vpcapi
        - name: DATABASE_SEARCHPATH
          value: public
        - name: DATABASE_CERT_SERVERNAME
          value: crdb-public.vpc-api.core-zero.us-east-03.int.coreweave.com
        - name: DATABASE_CERT_PKI
          value: pki/rsa/cw-gacrdbvpcapi
        - name: DATABASE_CERT_NAME
          value: vpc-api-crdb-tls
        - name: DATABASE_CERT_ROLE
          value: user
        - name: DATABASE_CERT_TTL
          value: 7d
        - name: DATABASE_CERT_COMMONNAME
          value: vpcapiadmin
        - name: TEMPORAL_NAMESPACE
          value: cks-platforms.kzw3l
        - name: TEMPORAL_HOST
          value: cks-platforms.kzw3l.tmprl.cloud:7233
        - name: TEMPORAL_CLIENT_CERT
          value: /var/run/ssl/certs/tls.crt
        - name: TEMPORAL_CLIENT_KEY
          value: /var/run/ssl/certs/tls.key
  vpc-api-worker-stag:
    valuesMerge:
      env:
        - name: ENVIRONMENT
          value: staging
        - name: ZONE
          value: us-east-04a
        - name: VAULT_CLIENT_URL
          value: https://secvault.int.coreweave.com
        - name: VAULT_CLIENT_JWT_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: VAULT_CLIENT_SECRETS_ROLE
          value: vpc-api-staging
        - name: DATABASE_ENDPOINT
          value: crdb-public.vpc-api-stg.core-zero.us-east-03.int.coreweave.com
        - name: DATABASE_USER
          value: vpcapiadmin
        - name: DATABASE_INSECURE
          value: "false"
        - name: DATABASE_DATABASENAME
          value: vpcapi
        - name: DATABASE_SEARCHPATH
          value: public
        - name: DATABASE_CERT_SERVERNAME
          value: crdb-public.vpc-api-stg.core-zero.us-east-03.int.coreweave.com
        - name: DATABASE_CERT_PKI
          value: pki/rsa/cw-gacrdbvpcapistg
        - name: DATABASE_CERT_NAME
          value: vpc-api-crdb-tls
        - name: DATABASE_CERT_ROLE
          value: user
        - name: DATABASE_CERT_TTL
          value: 7d
        - name: DATABASE_CERT_COMMONNAME
          value: vpcapiadmin
        - name: TEMPORAL_NAMESPACE
          value: cks-test-platforms.kzw3l
        - name: TEMPORAL_HOST
          value: cks-test-platforms.kzw3l.tmprl.cloud:7233
        - name: TEMPORAL_CLIENT_CERT
          value: /var/run/ssl/certs/tls.crt
        - name: TEMPORAL_CLIENT_KEY
          value: /var/run/ssl/certs/tls.key
