clusterSpec:
  region: us-west-03
  scope: cks
  clusterOrg: fe0dc0
  cni: cilium
  networkAllocations:
    podCIDRs: ["10.94.0.0/16"]
    serviceCIDRs: ["10.96.0.0/16"]
    internalLbCIDRs:
      default: 10.65.68.0/26
    additionalLbCIDRs:
      ipam:  192.112.171.0/24

argocd:
  targetClusterURL: https://kube-apiserver.tenant-fe0dc0-cks.svc.cluster.local

applications:
  cilium:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployCRs: false
      cilium:
        ipv4NativeRoutingCIDR: 10.64.0.0/10
        hubble:
          enabled: false
          metrics:
            enabled: null
          tls:
            enabled: false
          ui:
            enabled: false
          relay:
            enabled: false
  cilium-crs:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployLbPools: false
  calico:
    enabled: false
  calico-cleanup-controller:
    enabled: false
  control-plane:
    enabled: false
  cw-node-controller:
    valuesMerge:
      nodeLifeCycle:
        zapDpu: false
  external-secrets:
    enabled: false
  in-cluster-config:
    enabled: false
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.10"
  konnectivity-agent:
    enabled: false
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  coredns:
    namespace: null
    destination:
      server: https://kubernetes.default.svc
    valuesMerge:
      oob: true
      service:
        corednsOob:
          loadBalancerIP: "100.124.0.11"
      kubeconfig:
        cluster: fe0dc0-cks
        path: /etc/kubernetes/admin-config
      secretName: admin-kubeconfig
      monitoring:
        enabled: true
      extraServiceAnnotations:
        metallb.universe.tf/address-pool: tss
  node-local-dns:
    enabled: true
    valuesMerge:
      vast:
        enabled: true
      coreDnsOob: true
      coreDnsOobIP: "100.124.0.11"
      nldClusterIP: "10.96.0.30"
      coreDnsClusterIp: "10.96.0.10"
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: cks
            cluster_org: fe0dc0
            region: us-west-03
          config:
            lokiAddress: http://100.124.0.10/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  teleport:
    enabled: false
  traefik:
    enabled: false
  vector:
    enabled: false
  vast-csi-controller:
    valuesMerge:
      coreweave:
        clusterSecretStores:
          vast-fe0dc0-cks:
            project: vast
            config: prod_us-west-03a-automation
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-west-03-coreweave-us-west-03-ngcp
          namespace: victoria-metrics
