clusterSpec:
  region: us-east-04
  scope: k8s-beta-1
  clusterOrg: cw-internal
  cni: cilium
  networkAllocations:
    podCIDRs: [ "10.128.0.0/13" ]
    serviceCIDRs: ["10.32.0.0/22"]
    internalLbCIDRs:
      default: 10.32.4.0/22
    externalLbCIDRs:

argocd:
  targetClusterURL: https://kube-apiserver.tenant-cw-internal-k8s-beta-1.svc.cluster.local

applications:
  calico:
    enabled: false
  cilium:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.16.0
    valuesMerge:
      bgpVersion2: true
      deployCRs: false
  cilium-crs:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.16.0
    valuesMerge:
      bgpVersion2: true
      deployLbPools: false
  nodepools:
    enabled: true
    values:
      nodepools:
        cpu:
          targetNodes: 0
          instanceType: cd-hc-a384-genoa
  jspolicy-policies:
    values:
      policies:
        mutateNodeTypeGPU: false
  cw-node-controller:
    valuesMerge:
      nodeLifeCycle:
        zapDpu: false
  konnectivity-agent:
    enabled: false
  control-plane:
    enabled: false
  in-cluster-config:
    enabled: false
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.157"
  external-secrets:
    enabled: false
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  node-local-dns:
    valuesMerge:
      vast:
        enabled: true
  teleport:
    enabled: false
  traefik:
    enabled: false
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: k8s-beta-1
            cluster_org: cw-internal
            region: us-east-04
          config:
            lokiAddress: http://100.124.0.157/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  vast-csi:
    useAllTenantsVipPool: false
  cw-weka-operator:
    enabled: true
    valueFiles:
      - values-us-east-04a-cpu-lab.yaml
  cw-weka-cluster:
    enabled: true
    valueFiles:
      - values-us-east-04a-cpu-lab.yaml
  vector:
    enabled: false
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-04-coreweave-us-east-04-ngcp
          namespace: victoria-metrics
