clusterSpec:
  region: us-east-02
  scope: training2
  clusterOrg: 0c2a9a
  cni: cilium
  networkAllocations:
    additionalLbCIDRs:
      ipam: 166.19.9.0/24

argocd:
  targetClusterURL: https://kube-apiserver.tenant-0c2a9a-training2.svc.cluster.local

applications:
  calico:
    enabled: false
  calico-cleanup-controller:
    enabled: false
  cilium:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployCRs: false
      cilium:
        hubble:
          enabled: false
          metrics:
            enabled: null
          tls:
            enabled: false
          ui:
            enabled: false
          relay:
            enabled: false
  cilium-crs:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployLbPools: false
  control-plane:
    enabled: false
  cw-node-controller:
    valuesMerge:
      nodeLifeCycle:
        zapDpu: false
  external-secrets:
    enabled: false
  in-cluster-config:
    enabled: false
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.1"
  konnectivity-agent:
    enabled: false
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  coredns:
    namespace: null
    destination:
      server: https://kubernetes.default.svc
    valuesMerge:
      oob: true
      service:
        corednsOob:
          loadBalancerIP: "100.124.0.229"
      kubeconfig:
        cluster: 0c2a9a-training2
        path: /etc/kubernetes/admin-config
      secretName: internal-admin-kubeconfig
      monitoring:
        enabled: true
      extraServiceAnnotations:
        metallb.universe.tf/address-pool: tss
  node-local-dns:
    valuesMerge:
      vast:
        enabled: true
      coreDnsOob: true
      coreDnsOobIP: "100.124.0.229"
      nldClusterIP: "10.16.0.30"
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: training2
            cluster_org: 0c2a9a
            region: us-east-02
          config:
            lokiAddress: http://100.124.0.1/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  teleport:
    enabled: false
  traefik:
    enabled: false
  vast-csi:
    valuesMerge:
      storageClasses:
        shared-vast:
          vipPool: 0c2a9a-training2
          viewPolicy: nosquash-0c2a9a-training2
  vector:
    enabled: false
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-02-coreweave-us-east-02-ngcp
          namespace: victoria-metrics
