clusterSpec:
  scope: workload
applications:
  calico:
    enabled: true
  cert-manager:
    enabled: true
  control-plane:
    enabled: true
    valuesMerge:
      konnectivity:
        enabled: true
  coredns:
    enabled: true
  crowdstrike:
    enabled: true
  epimetheus:
    enabled: true
  hpc-verification:
    enabled: true
  in-cluster-config:
    enabled: true
  jspolicy:
    enabled: true
  kubemod:
    enabled: true
  local-storage-provisioner:
    enabled: true
  loki:
    enabled: true
  konnectivity-agent:
    enabled: true
  metallb:
    enabled: true
  metrics:
    enabled: true
  metrics-server:
    enabled: true
  multus:
    enabled: true
  multus-cni:
    enabled: true
  nfd:
    enabled: true
  node-pci-exporter:
    enabled: true
    targetRevision: node-pci-exporter-v1.6.0
    syncPolicy:
      automated: {}
  node-problem-detector:
    enabled: true
  nvidia-device-plugin:
    enabled: true
  oidc:
    enabled: true
  promtail:
    enabled: true
  pvmo:
    enabled: true
  rooker-cluster:
    enabled: true
  rooker-operator:
    enabled: true
  teleport:
    enabled: true
  traefik:
    enabled: true
