clusterSpec:
  region: rno2
  scope: fleetops
  clusterOrg: cw-internal
  cni: cilium
  networkAllocations:
    externalLbCIDRs:

argocd:
  targetClusterURL: https://kube-apiserver.tenant-cw-internal-fleetops.svc.cluster.local

applications:
  fleetops-cluster:
    enabled: true
    appName: fleetops-cluster-rno2
    valuesMerge:
      k8sVersion: v1.30
  jspolicy-policies:
    values:
      policies:
        mutateNodeTypeGPU: false
  konnectivity-agent:
    enabled: false
  calico-cleanup-controller:
    enabled: false
  cilium:
    enabled: true
    valuesMerge:
      cilium:
        enableIPv4BIGTCP: false
      coreweave:
        clusterSecretStores:
        externalSecrets:
  calico:
    enabled: false
  control-plane:
    enabled: false
  in-cluster-config:
    enabled: false
  coredns:
    namespace: null
    destination:
      server: https://kubernetes.default.svc
    valuesMerge:
      oob: true
      service:
        corednsOob:
          loadBalancerIP: "100.124.0.60"
      kubeconfig:
        cluster: cw-internal-fleetops
        path: /etc/kubernetes/admin-config
      secretName: admin-kubeconfig
      monitoring:
        enabled: true
      extraServiceAnnotations:
        metallb.universe.tf/address-pool: tss
  node-local-dns:
    enabled: true
    valuesMerge:
      coreDnsOob: true
      coreDnsOobIP: "100.124.0.60"
      nldClusterIP: "10.16.0.30"
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.57"
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  teleport:
    enabled: false
  traefik:
    enabled: false
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: fleetops
            cluster_org: cw-internal
            region: rno2
          config:
            lokiAddress: http://100.124.0.57/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  # vast-csi:
  #   hasDedicatedTenant: true
  vector:
    enabled: false
  remote-dns:
    enabled: false
  eclypsium-scans:
    enabled: true
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-rno2-coreweave-rno2-ngcp
          namespace: victoria-metrics
