clusterSpec:
  region: us-east-08
  scope: prod-us-east-08
  clusterOrg: 189d5b
  cni: cilium
  networkAllocations:
    additionalLbCIDRs:
      ipam: 166.19.14.0/23
    internalLbCIDRs:
      regional: "10.16.12.0/22"

argocd:
  targetClusterURL: https://kube-apiserver.tenant-189d5b-prod-us-east-08.svc.cluster.local

applications:
  node-problem-detector:
    targetRevision: 1.37.0
  cilium:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.18.0 # tuning sysctls for osov1 performance
    valuesMerge:
      bgpVersion2: true
      deployCRs: false
      pmtuDiscovery:
        enabled: true
      cilium:
        ipv4NativeRoutingCIDR: 10.0.0.0/13
        hubble:
          enabled: false
          metrics:
            enabled: null
          tls:
            enabled: false
          ui:
            enabled: false
          relay:
            enabled: false
  cilium-crs:
    enabled: true
    repoURL: https://charts.core-services.ingress.int.coreweave.com/k8s-services
    targetRevision: 1.17.0
    valuesMerge:
      bgpVersion2: true
      deployLbPools: false
  calico:
    enabled: false
  calico-cleanup-controller:
    enabled: false
  control-plane:
    enabled: false
  cw-node-controller:
    valuesMerge:
      nodeLifeCycle:
        zapDpu: false
  external-secrets:
    enabled: false
  in-cluster-config:
    enabled: false
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.11"
  konnectivity-agent:
    enabled: false
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  coredns:
    namespace: null
    destination:
      server: https://kubernetes.default.svc
    valuesMerge:
      oob: true
      service:
        corednsOob:
          loadBalancerIP: "100.124.0.15"
      kubeconfig:
        cluster: 189d5b-prod-us-east-08
        path: /etc/kubernetes/admin-config
      secretName: internal-admin-kubeconfig
      monitoring:
        enabled: true
      extraServiceAnnotations:
        metallb.universe.tf/address-pool: tss
  node-local-dns:
    enabled: true
    valuesMerge:
      vast:
        enabled: true
      coreDnsOob: true
      coreDnsOobIP: "100.124.0.15"
      nldClusterIP: "10.16.0.30"
  nodepools:
    enabled: true
    values:
      nodepools:
        cpu-control-plane:
          targetNodes: 2
          instanceType: cd-gp-i64-erapids
        cpu:
          targetNodes: 10
          instanceType: cd-gp-i64-erapids
        gpu-h200:
          targetNodes: 400
          instanceType: gd-8xh200ib-i128
        gpu-h200-buffer:
          targetNodes: 10
          instanceType: gd-8xh200ib-i128
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: prod-us-east-08
            cluster_org: 189d5b
            region: us-east-08
          config:
            lokiAddress: http://100.124.0.11/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  teleport:
    enabled: false
  traefik:
    enabled: false
  vast-csi:
    targetRevision: 1.55.0
    valuesMerge:
      storageClasses:
        shared-vast:
          vipPool: 189d5b-prod-us-east-08
          viewPolicy: nosquash-189d5b-prod-us-east-08
          mountOptions:
            - vers=3
            - nconnect=16
            - lookupcache=pos
            - noacl
            - noatime
            - remoteports=100.121.3.1-100.121.3.136
  vector:
    enabled: false
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-08-coreweave-us-east-08a-ngcp
          namespace: victoria-metrics
