clusterSpec:
  region: us-east-04
  scope: ml-poc
  clusterOrg: cw-internal
  networkAllocations:
    additionalLbCIDRs:
      ipam: 166.19.16.0/23

argocd:
  targetClusterURL: https://kube-apiserver.tenant-cw-internal-ml-poc.svc.cluster.local
applications:
  jspolicy-policies:
    values:
      policies:
        mutateNodeTypeGPU: false
  # control-plane & etcd are managed by the Katalyst operator
  control-plane:
    enabled: false
  # katalyst operator manages the konnectivity-agent deployment
  konnectivity-agent:
    enabled: false
  calico-cleanup-controller:
    enabled: true
  calico:
    enabled: true
    valuesMerge:
      typha:
        replicas: 2
  in-cluster-config:
    enabled: false
  node-local-dns:
    enabled: true
  nodepools:
    enabled: true
    values:
      nodepools:
        cpu-control-plane:
          targetNodes: 2
        gpu-a100:
          targetNodes: 4
          instanceType: gd-8xa100-i128
        cpu-genoa:
          instanceType: cd-hc-a384-genoa
          targetNodes: 3
        gpu-h100:
          targetNodes: 4
          instanceType: gd-8xh100ib-i128
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: 100.124.0.130
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: ml-poc
            cluster_org: cw-internal
            region: us-east-04
          config:
            lokiAddress: http://100.124.0.130/loki/api/v1/push
  # Teleport is managed by the katalyst-operator
  teleport:
    enabled: false
  # vast-csi:
  #   hasDedicatedTenant: true
  vast-csi:
    useAllTenantsVipPool: false
    valuesMerge:
      storageClasses:
        shared-vast:
          vipPool: cw-internal-ml-poc
          viewPolicy: nosquash-cw-internal-ml-poc
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-04-coreweave-us-east-04-ngcp
          namespace: victoria-metrics
