clusterSpec:
  region: us-east-02
  scope: fleetops
  clusterOrg: cw-internal
  cni: cilium
  networkAllocations:
    externalLbCIDRs:

argocd:
  targetClusterURL: https://kube-apiserver.tenant-cw-internal-fleetops.svc.cluster.local

applications:
  # this fleetops cluster was created by hand, do not use the templated application
  fleetops-cluster:
    enabled: false
  jspolicy-policies:
    values:
      policies:
        mutateNodeTypeGPU: false
  cw-node-controller:
    valuesMerge:
      controllerConfig:
        controlPlaneNodes: "g5b6554,g5bac94"
  konnectivity-agent:
    enabled: false
  calico-cleanup-controller:
    enabled: false
  cilium:
    enabled: true
    valuesMerge:
      coreweave:
        clusterSecretStores:
        externalSecrets:
  calico:
    enabled: false
  control-plane:
    enabled: false
  in-cluster-config:
    enabled: false
  coredns:
    namespace: null
    destination:
      server: https://kubernetes.default.svc
    valuesMerge:
      oob: true
      service:
        corednsOob:
          loadBalancerIP: "100.124.0.230"
      kubeconfig:
        cluster: cw-internal-fleetops
        path: /etc/kubernetes/admin-config
      secretName: internal-admin-kubeconfig
      monitoring:
        enabled: true
      extraServiceAnnotations:
        metallb.universe.tf/address-pool: tss
  node-local-dns:
    enabled: true
    valuesMerge:
      coreDnsOob: true
      coreDnsOobIP: "100.124.0.230"
      nldClusterIP: "10.16.0.30"
  katalyst-proxy:
    valuesMerge:
      loadBalancerIP: "100.124.0.18"
  metrics:
    valuesMerge:
      prometheus-operator:
        kubeApiServer:
          enabled: false
  teleport:
    enabled: false
  traefik:
    enabled: false
  promtail:
    valuesMerge:
      promtail:
        promtail:
          coreweaveLabels:
            cluster: fleetops
            cluster_org: cw-internal
            region: us-east-02
          config:
            lokiAddress: http://100.124.0.18/loki/api/v1/push
  rook-ceph:
    enabled: false
  rook-operator:
    enabled: false
  # vast-csi:
  #   hasDedicatedTenant: true
  vector:
    enabled: false
  pvmo:
    valuesMerge:
      monitoring:
        enabled: true
        serviceAccount:
          name: vmagent-us-east-02-coreweave-us-east-02-ngcp
          namespace: victoria-metrics
