applications:
  nfd:
    valuesMerge:
      worker:
        image: ghcr.io/coreweave/nascd/nfd/node-feature-discovery:multi-arch-0.9.0
  node-pci-exporter:
    valuesMerge:
      image: ghcr.io/coreweave/nascd/node-pci-exporter:v1.5.0-multi-arch
      env:
      - name: PCI_TARGETS
        value: "10de:2330,15b3:1021,15b3:a2d6,8086:352a,15b3:101d,1000:c030,10de:22a3,10de:20b2,15b3:101b,8086:347a,1000:c010,10de:1af1,10de:26b5,10de:26b9,10de:2342,15b3:a2dc"
  nvidia-device-plugin:
    valuesMerge:
      image: ghcr.io/coreweave/nascd/k8s-device-plugin:multi-arch-0
      initContainerImage: ubuntu:20.04
  multus-cni:
    valuesMerge:
      daemonset:
        image:
          repository: ghcr.io/coreweave/nascd/multus-cni/multus-cni
          tag: multi-arch-3.9
  promtail:
    valuesMerge:
      promtail:
        promtail:
          image:
            tag: 3.2.0
