{{- range $name, $spec := .Values.coreweave.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $name }}
spec:
  provider:
    doppler:
      project: {{ required (printf "ClusterSecretStore %v must specify which project it has access to within doppler." $spec.project) $spec.project }}
      config: {{ required (printf "ClusterSecretStore %v must specify which config it has access to within a project." $spec.config) $spec.config }}
      auth:
        secretRef:
          dopplerToken:
            name: {{ if hasKey $spec "overrideDopplerTokenName" }}{{ $spec.overrideDopplerTokenName }}{{ else }}doppler-token-auth-api{{ end }}
            key: {{ if hasKey $spec "overrideDopplerTokenKey" }}{{ $spec.overrideDopplerTokenKey }}{{ else }}dopplerToken{{ end }}
            namespace: {{ if hasKey $spec "overrideDopplerTokenNamespace" }}{{ $spec.overrideDopplerTokenNamespace }}{{ else }}external-secrets{{ end }}
  conditions:
    - namespaces:
    {{- if hasKey $spec "namespaces" }}
      {{- range $namespace := $spec.namespaces }}
      - {{ $namespace }}
      {{- end }}
      {{- if not (has $.Release.Namespace $spec.namespaces) }}
      - {{ $.Release.Namespace }}
      {{- end }}
    {{- else }}
      - {{ $.Release.Namespace }}
    {{- end }}
{{- end }}
