{{- range $key, $value := .Values.coreweave.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
{{ $value | toYaml | indent 4 }}
  template:
    metadata:
      name: {{ $key }}
      namespace: {{ $.Release.Namespace }}
    type: Opaque
{{- end }}
